### ISSUE TITLE
do errors thrown in initialisers cause an abrupt completion of construction?

### ISSUE THREAD

**Issue by michaelficarra** [jeffmo/es-class-properties#10]
``` js
class A {
  b = (_ => { throw 0; })();
  c = f();
  constructor() {
    g();
  }
}
```

Is `f()` evaluated? Is `g()`? Does `new A` throw? If not, what is the value of `new A().b`?

**Comment by fatfisz** [comment]
`f()` will be evaluated when `new A()` is executed.
The same for `g()`.
`new A` should throw when `b`'s initializer is executed.

Amirite?

**Comment by jeffmo** [comment]
`new A` will throw and neither `f()`, nor the `constructor()` method itself will be evaluated here.

**Comment by michaelficarra** [comment]
So `new A` is guaranteed to evaluate the initialiser of `b` before the initialiser of `c` and before the constructor body?

**Comment by jeffmo** [comment]
Yes: https://github.com/jeffmo/es-class-static-properties-and-fields#instance-field-initialization-process

> intended to run once for each field in the order they are declared
