### ISSUE TITLE
Link this back to tc39

### ISSUE THREAD

**Issue by whitneyit** [jeffmo/es-class-properties#29]
Similar to your [gist](https://gist.github.com/jeffmo/054df782c05639da2adb) that labels this proposal as stage 0, would you be able to add which stage this proposal is currently in and link that back to https://github.com/tc39/ecma262

I'll be happy to submit a PR to add this as a header if you would prefer

**Comment by wmertens** [comment]
This is done and this issue can be closed, right?

**Comment by whitneyit** [comment]
I was referring to adding **~~ NOTE: This is a [Stage 1](https://github.com/tc39/ecma262) proposal. ~~** to the [README.md](https://github.com/jeffmo/es-class-fields-and-static-properties/blob/864e92d09f895c9b28e1c745544058ea662b0e06/README.md)

**Comment by jeffmo** [comment]
Ah my bad -- PR welcome!
