### ISSUE TITLE
Property descriptor looks wrong in step 2 of "Instance Property Initialization Process"

### ISSUE THREAD

**Issue by ajklein** [jeffmo/es-class-properties#3]
The descriptor is:

``` js
{
  configurable: true,
  enumerable: true,
  writable: true,
  get: undefined,
  set: undefined,
}
```

But should presumably be:

``` js
{
  configurable: true,
  enumerable: true,
  writable: true,
  value: resultOfInitializerFunction
}
```

**Comment by ajklein** [comment]
The same problem appears in step 6 of the process for initializing static properties.

**Comment by jeffmo** [comment]
Sorry, I left this out thinking it was implicit -- but I can see how this could be ambiguous. Thanks for pointing this out

Fixed in https://github.com/jeffmo/es-class-properties/commit/7643fbf990733170bcfb30bc4b4651fe369cf87c
