### ISSUE TITLE
do not handle thunking of intiialisation expression using "function wrapper"

### ISSUE THREAD

**Issue by michaelficarra** [jeffmo/es-class-properties#8]
A much better way to do it is to capture the ECMAScript code itself as well as the current environment record. Save that, then it can be evaluated later. Additionally, this will clarify that constructor parameters, `arguments`, and `new.target` are all not available. Something special will have to be done regarding `this` for instance properties.

**Comment by jeffmo** [comment]
This is now how the proposal is specified: https://jeffmo.github.io/es-class-public-fields/#initialize-public-instance-fields
